
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KodWeryfikacyjny` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model KodWeryfikacyjny
 * 
 */
export type KodWeryfikacyjnyModel = runtime.Types.Result.DefaultSelection<Prisma.$KodWeryfikacyjnyPayload>

export type AggregateKodWeryfikacyjny = {
  _count: KodWeryfikacyjnyCountAggregateOutputType | null
  _avg: KodWeryfikacyjnyAvgAggregateOutputType | null
  _sum: KodWeryfikacyjnySumAggregateOutputType | null
  _min: KodWeryfikacyjnyMinAggregateOutputType | null
  _max: KodWeryfikacyjnyMaxAggregateOutputType | null
}

export type KodWeryfikacyjnyAvgAggregateOutputType = {
  probyNieudane: number | null
}

export type KodWeryfikacyjnySumAggregateOutputType = {
  probyNieudane: number | null
}

export type KodWeryfikacyjnyMinAggregateOutputType = {
  id: string | null
  uzytkownikId: string | null
  kodHash: string | null
  probyNieudane: number | null
  wygasaAt: Date | null
  wykorzystanyAt: Date | null
  utworzonyAt: Date | null
}

export type KodWeryfikacyjnyMaxAggregateOutputType = {
  id: string | null
  uzytkownikId: string | null
  kodHash: string | null
  probyNieudane: number | null
  wygasaAt: Date | null
  wykorzystanyAt: Date | null
  utworzonyAt: Date | null
}

export type KodWeryfikacyjnyCountAggregateOutputType = {
  id: number
  uzytkownikId: number
  kodHash: number
  probyNieudane: number
  wygasaAt: number
  wykorzystanyAt: number
  utworzonyAt: number
  _all: number
}


export type KodWeryfikacyjnyAvgAggregateInputType = {
  probyNieudane?: true
}

export type KodWeryfikacyjnySumAggregateInputType = {
  probyNieudane?: true
}

export type KodWeryfikacyjnyMinAggregateInputType = {
  id?: true
  uzytkownikId?: true
  kodHash?: true
  probyNieudane?: true
  wygasaAt?: true
  wykorzystanyAt?: true
  utworzonyAt?: true
}

export type KodWeryfikacyjnyMaxAggregateInputType = {
  id?: true
  uzytkownikId?: true
  kodHash?: true
  probyNieudane?: true
  wygasaAt?: true
  wykorzystanyAt?: true
  utworzonyAt?: true
}

export type KodWeryfikacyjnyCountAggregateInputType = {
  id?: true
  uzytkownikId?: true
  kodHash?: true
  probyNieudane?: true
  wygasaAt?: true
  wykorzystanyAt?: true
  utworzonyAt?: true
  _all?: true
}

export type KodWeryfikacyjnyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KodWeryfikacyjny to aggregate.
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KodWeryfikacyjnies to fetch.
   */
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithRelationInput | Prisma.KodWeryfikacyjnyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KodWeryfikacyjnyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KodWeryfikacyjnies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KodWeryfikacyjnies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KodWeryfikacyjnies
  **/
  _count?: true | KodWeryfikacyjnyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KodWeryfikacyjnyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KodWeryfikacyjnySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KodWeryfikacyjnyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KodWeryfikacyjnyMaxAggregateInputType
}

export type GetKodWeryfikacyjnyAggregateType<T extends KodWeryfikacyjnyAggregateArgs> = {
      [P in keyof T & keyof AggregateKodWeryfikacyjny]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKodWeryfikacyjny[P]>
    : Prisma.GetScalarType<T[P], AggregateKodWeryfikacyjny[P]>
}




export type KodWeryfikacyjnyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KodWeryfikacyjnyWhereInput
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithAggregationInput | Prisma.KodWeryfikacyjnyOrderByWithAggregationInput[]
  by: Prisma.KodWeryfikacyjnyScalarFieldEnum[] | Prisma.KodWeryfikacyjnyScalarFieldEnum
  having?: Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KodWeryfikacyjnyCountAggregateInputType | true
  _avg?: KodWeryfikacyjnyAvgAggregateInputType
  _sum?: KodWeryfikacyjnySumAggregateInputType
  _min?: KodWeryfikacyjnyMinAggregateInputType
  _max?: KodWeryfikacyjnyMaxAggregateInputType
}

export type KodWeryfikacyjnyGroupByOutputType = {
  id: string
  uzytkownikId: string
  kodHash: string
  probyNieudane: number
  wygasaAt: Date
  wykorzystanyAt: Date | null
  utworzonyAt: Date
  _count: KodWeryfikacyjnyCountAggregateOutputType | null
  _avg: KodWeryfikacyjnyAvgAggregateOutputType | null
  _sum: KodWeryfikacyjnySumAggregateOutputType | null
  _min: KodWeryfikacyjnyMinAggregateOutputType | null
  _max: KodWeryfikacyjnyMaxAggregateOutputType | null
}

type GetKodWeryfikacyjnyGroupByPayload<T extends KodWeryfikacyjnyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KodWeryfikacyjnyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KodWeryfikacyjnyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KodWeryfikacyjnyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KodWeryfikacyjnyGroupByOutputType[P]>
      }
    >
  >



export type KodWeryfikacyjnyWhereInput = {
  AND?: Prisma.KodWeryfikacyjnyWhereInput | Prisma.KodWeryfikacyjnyWhereInput[]
  OR?: Prisma.KodWeryfikacyjnyWhereInput[]
  NOT?: Prisma.KodWeryfikacyjnyWhereInput | Prisma.KodWeryfikacyjnyWhereInput[]
  id?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  uzytkownikId?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  kodHash?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  probyNieudane?: Prisma.IntFilter<"KodWeryfikacyjny"> | number
  wygasaAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
  wykorzystanyAt?: Prisma.DateTimeNullableFilter<"KodWeryfikacyjny"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
  uzytkownik?: Prisma.XOR<Prisma.UzytkownikScalarRelationFilter, Prisma.UzytkownikWhereInput>
}

export type KodWeryfikacyjnyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  uzytkownikId?: Prisma.SortOrder
  kodHash?: Prisma.SortOrder
  probyNieudane?: Prisma.SortOrder
  wygasaAt?: Prisma.SortOrder
  wykorzystanyAt?: Prisma.SortOrderInput | Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
  uzytkownik?: Prisma.UzytkownikOrderByWithRelationInput
}

export type KodWeryfikacyjnyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KodWeryfikacyjnyWhereInput | Prisma.KodWeryfikacyjnyWhereInput[]
  OR?: Prisma.KodWeryfikacyjnyWhereInput[]
  NOT?: Prisma.KodWeryfikacyjnyWhereInput | Prisma.KodWeryfikacyjnyWhereInput[]
  uzytkownikId?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  kodHash?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  probyNieudane?: Prisma.IntFilter<"KodWeryfikacyjny"> | number
  wygasaAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
  wykorzystanyAt?: Prisma.DateTimeNullableFilter<"KodWeryfikacyjny"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
  uzytkownik?: Prisma.XOR<Prisma.UzytkownikScalarRelationFilter, Prisma.UzytkownikWhereInput>
}, "id">

export type KodWeryfikacyjnyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  uzytkownikId?: Prisma.SortOrder
  kodHash?: Prisma.SortOrder
  probyNieudane?: Prisma.SortOrder
  wygasaAt?: Prisma.SortOrder
  wykorzystanyAt?: Prisma.SortOrderInput | Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
  _count?: Prisma.KodWeryfikacyjnyCountOrderByAggregateInput
  _avg?: Prisma.KodWeryfikacyjnyAvgOrderByAggregateInput
  _max?: Prisma.KodWeryfikacyjnyMaxOrderByAggregateInput
  _min?: Prisma.KodWeryfikacyjnyMinOrderByAggregateInput
  _sum?: Prisma.KodWeryfikacyjnySumOrderByAggregateInput
}

export type KodWeryfikacyjnyScalarWhereWithAggregatesInput = {
  AND?: Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput | Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput[]
  OR?: Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput | Prisma.KodWeryfikacyjnyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KodWeryfikacyjny"> | string
  uzytkownikId?: Prisma.StringWithAggregatesFilter<"KodWeryfikacyjny"> | string
  kodHash?: Prisma.StringWithAggregatesFilter<"KodWeryfikacyjny"> | string
  probyNieudane?: Prisma.IntWithAggregatesFilter<"KodWeryfikacyjny"> | number
  wygasaAt?: Prisma.DateTimeWithAggregatesFilter<"KodWeryfikacyjny"> | Date | string
  wykorzystanyAt?: Prisma.DateTimeNullableWithAggregatesFilter<"KodWeryfikacyjny"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeWithAggregatesFilter<"KodWeryfikacyjny"> | Date | string
}

export type KodWeryfikacyjnyCreateInput = {
  id?: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
  uzytkownik: Prisma.UzytkownikCreateNestedOneWithoutKodyInput
}

export type KodWeryfikacyjnyUncheckedCreateInput = {
  id?: string
  uzytkownikId: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type KodWeryfikacyjnyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  uzytkownik?: Prisma.UzytkownikUpdateOneRequiredWithoutKodyNestedInput
}

export type KodWeryfikacyjnyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uzytkownikId?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KodWeryfikacyjnyCreateManyInput = {
  id?: string
  uzytkownikId: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type KodWeryfikacyjnyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KodWeryfikacyjnyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uzytkownikId?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KodWeryfikacyjnyListRelationFilter = {
  every?: Prisma.KodWeryfikacyjnyWhereInput
  some?: Prisma.KodWeryfikacyjnyWhereInput
  none?: Prisma.KodWeryfikacyjnyWhereInput
}

export type KodWeryfikacyjnyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KodWeryfikacyjnyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uzytkownikId?: Prisma.SortOrder
  kodHash?: Prisma.SortOrder
  probyNieudane?: Prisma.SortOrder
  wygasaAt?: Prisma.SortOrder
  wykorzystanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type KodWeryfikacyjnyAvgOrderByAggregateInput = {
  probyNieudane?: Prisma.SortOrder
}

export type KodWeryfikacyjnyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uzytkownikId?: Prisma.SortOrder
  kodHash?: Prisma.SortOrder
  probyNieudane?: Prisma.SortOrder
  wygasaAt?: Prisma.SortOrder
  wykorzystanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type KodWeryfikacyjnyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uzytkownikId?: Prisma.SortOrder
  kodHash?: Prisma.SortOrder
  probyNieudane?: Prisma.SortOrder
  wygasaAt?: Prisma.SortOrder
  wykorzystanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type KodWeryfikacyjnySumOrderByAggregateInput = {
  probyNieudane?: Prisma.SortOrder
}

export type KodWeryfikacyjnyCreateNestedManyWithoutUzytkownikInput = {
  create?: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput> | Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput[] | Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput[]
  connectOrCreate?: Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput[]
  createMany?: Prisma.KodWeryfikacyjnyCreateManyUzytkownikInputEnvelope
  connect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
}

export type KodWeryfikacyjnyUncheckedCreateNestedManyWithoutUzytkownikInput = {
  create?: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput> | Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput[] | Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput[]
  connectOrCreate?: Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput[]
  createMany?: Prisma.KodWeryfikacyjnyCreateManyUzytkownikInputEnvelope
  connect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
}

export type KodWeryfikacyjnyUpdateManyWithoutUzytkownikNestedInput = {
  create?: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput> | Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput[] | Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput[]
  connectOrCreate?: Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput[]
  upsert?: Prisma.KodWeryfikacyjnyUpsertWithWhereUniqueWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpsertWithWhereUniqueWithoutUzytkownikInput[]
  createMany?: Prisma.KodWeryfikacyjnyCreateManyUzytkownikInputEnvelope
  set?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  disconnect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  delete?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  connect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  update?: Prisma.KodWeryfikacyjnyUpdateWithWhereUniqueWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpdateWithWhereUniqueWithoutUzytkownikInput[]
  updateMany?: Prisma.KodWeryfikacyjnyUpdateManyWithWhereWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpdateManyWithWhereWithoutUzytkownikInput[]
  deleteMany?: Prisma.KodWeryfikacyjnyScalarWhereInput | Prisma.KodWeryfikacyjnyScalarWhereInput[]
}

export type KodWeryfikacyjnyUncheckedUpdateManyWithoutUzytkownikNestedInput = {
  create?: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput> | Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput[] | Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput[]
  connectOrCreate?: Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput[]
  upsert?: Prisma.KodWeryfikacyjnyUpsertWithWhereUniqueWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpsertWithWhereUniqueWithoutUzytkownikInput[]
  createMany?: Prisma.KodWeryfikacyjnyCreateManyUzytkownikInputEnvelope
  set?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  disconnect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  delete?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  connect?: Prisma.KodWeryfikacyjnyWhereUniqueInput | Prisma.KodWeryfikacyjnyWhereUniqueInput[]
  update?: Prisma.KodWeryfikacyjnyUpdateWithWhereUniqueWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpdateWithWhereUniqueWithoutUzytkownikInput[]
  updateMany?: Prisma.KodWeryfikacyjnyUpdateManyWithWhereWithoutUzytkownikInput | Prisma.KodWeryfikacyjnyUpdateManyWithWhereWithoutUzytkownikInput[]
  deleteMany?: Prisma.KodWeryfikacyjnyScalarWhereInput | Prisma.KodWeryfikacyjnyScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type KodWeryfikacyjnyCreateWithoutUzytkownikInput = {
  id?: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput = {
  id?: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type KodWeryfikacyjnyCreateOrConnectWithoutUzytkownikInput = {
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
  create: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput>
}

export type KodWeryfikacyjnyCreateManyUzytkownikInputEnvelope = {
  data: Prisma.KodWeryfikacyjnyCreateManyUzytkownikInput | Prisma.KodWeryfikacyjnyCreateManyUzytkownikInput[]
}

export type KodWeryfikacyjnyUpsertWithWhereUniqueWithoutUzytkownikInput = {
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
  update: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedUpdateWithoutUzytkownikInput>
  create: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedCreateWithoutUzytkownikInput>
}

export type KodWeryfikacyjnyUpdateWithWhereUniqueWithoutUzytkownikInput = {
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateWithoutUzytkownikInput, Prisma.KodWeryfikacyjnyUncheckedUpdateWithoutUzytkownikInput>
}

export type KodWeryfikacyjnyUpdateManyWithWhereWithoutUzytkownikInput = {
  where: Prisma.KodWeryfikacyjnyScalarWhereInput
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateManyMutationInput, Prisma.KodWeryfikacyjnyUncheckedUpdateManyWithoutUzytkownikInput>
}

export type KodWeryfikacyjnyScalarWhereInput = {
  AND?: Prisma.KodWeryfikacyjnyScalarWhereInput | Prisma.KodWeryfikacyjnyScalarWhereInput[]
  OR?: Prisma.KodWeryfikacyjnyScalarWhereInput[]
  NOT?: Prisma.KodWeryfikacyjnyScalarWhereInput | Prisma.KodWeryfikacyjnyScalarWhereInput[]
  id?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  uzytkownikId?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  kodHash?: Prisma.StringFilter<"KodWeryfikacyjny"> | string
  probyNieudane?: Prisma.IntFilter<"KodWeryfikacyjny"> | number
  wygasaAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
  wykorzystanyAt?: Prisma.DateTimeNullableFilter<"KodWeryfikacyjny"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeFilter<"KodWeryfikacyjny"> | Date | string
}

export type KodWeryfikacyjnyCreateManyUzytkownikInput = {
  id?: string
  kodHash: string
  probyNieudane?: number
  wygasaAt: Date | string
  wykorzystanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type KodWeryfikacyjnyUpdateWithoutUzytkownikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KodWeryfikacyjnyUncheckedUpdateWithoutUzytkownikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KodWeryfikacyjnyUncheckedUpdateManyWithoutUzytkownikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kodHash?: Prisma.StringFieldUpdateOperationsInput | string
  probyNieudane?: Prisma.IntFieldUpdateOperationsInput | number
  wygasaAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wykorzystanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type KodWeryfikacyjnySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uzytkownikId?: boolean
  kodHash?: boolean
  probyNieudane?: boolean
  wygasaAt?: boolean
  wykorzystanyAt?: boolean
  utworzonyAt?: boolean
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kodWeryfikacyjny"]>

export type KodWeryfikacyjnySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uzytkownikId?: boolean
  kodHash?: boolean
  probyNieudane?: boolean
  wygasaAt?: boolean
  wykorzystanyAt?: boolean
  utworzonyAt?: boolean
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kodWeryfikacyjny"]>

export type KodWeryfikacyjnySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uzytkownikId?: boolean
  kodHash?: boolean
  probyNieudane?: boolean
  wygasaAt?: boolean
  wykorzystanyAt?: boolean
  utworzonyAt?: boolean
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kodWeryfikacyjny"]>

export type KodWeryfikacyjnySelectScalar = {
  id?: boolean
  uzytkownikId?: boolean
  kodHash?: boolean
  probyNieudane?: boolean
  wygasaAt?: boolean
  wykorzystanyAt?: boolean
  utworzonyAt?: boolean
}

export type KodWeryfikacyjnyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "uzytkownikId" | "kodHash" | "probyNieudane" | "wygasaAt" | "wykorzystanyAt" | "utworzonyAt", ExtArgs["result"]["kodWeryfikacyjny"]>
export type KodWeryfikacyjnyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}
export type KodWeryfikacyjnyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}
export type KodWeryfikacyjnyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  uzytkownik?: boolean | Prisma.UzytkownikDefaultArgs<ExtArgs>
}

export type $KodWeryfikacyjnyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KodWeryfikacyjny"
  objects: {
    uzytkownik: Prisma.$UzytkownikPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    uzytkownikId: string
    kodHash: string
    probyNieudane: number
    wygasaAt: Date
    wykorzystanyAt: Date | null
    utworzonyAt: Date
  }, ExtArgs["result"]["kodWeryfikacyjny"]>
  composites: {}
}

export type KodWeryfikacyjnyGetPayload<S extends boolean | null | undefined | KodWeryfikacyjnyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload, S>

export type KodWeryfikacyjnyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KodWeryfikacyjnyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KodWeryfikacyjnyCountAggregateInputType | true
  }

export interface KodWeryfikacyjnyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KodWeryfikacyjny'], meta: { name: 'KodWeryfikacyjny' } }
  /**
   * Find zero or one KodWeryfikacyjny that matches the filter.
   * @param {KodWeryfikacyjnyFindUniqueArgs} args - Arguments to find a KodWeryfikacyjny
   * @example
   * // Get one KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KodWeryfikacyjnyFindUniqueArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KodWeryfikacyjny that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KodWeryfikacyjnyFindUniqueOrThrowArgs} args - Arguments to find a KodWeryfikacyjny
   * @example
   * // Get one KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KodWeryfikacyjnyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KodWeryfikacyjny that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyFindFirstArgs} args - Arguments to find a KodWeryfikacyjny
   * @example
   * // Get one KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KodWeryfikacyjnyFindFirstArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyFindFirstArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KodWeryfikacyjny that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyFindFirstOrThrowArgs} args - Arguments to find a KodWeryfikacyjny
   * @example
   * // Get one KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KodWeryfikacyjnyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KodWeryfikacyjnies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KodWeryfikacyjnies
   * const kodWeryfikacyjnies = await prisma.kodWeryfikacyjny.findMany()
   * 
   * // Get first 10 KodWeryfikacyjnies
   * const kodWeryfikacyjnies = await prisma.kodWeryfikacyjny.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kodWeryfikacyjnyWithIdOnly = await prisma.kodWeryfikacyjny.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KodWeryfikacyjnyFindManyArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KodWeryfikacyjny.
   * @param {KodWeryfikacyjnyCreateArgs} args - Arguments to create a KodWeryfikacyjny.
   * @example
   * // Create one KodWeryfikacyjny
   * const KodWeryfikacyjny = await prisma.kodWeryfikacyjny.create({
   *   data: {
   *     // ... data to create a KodWeryfikacyjny
   *   }
   * })
   * 
   */
  create<T extends KodWeryfikacyjnyCreateArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyCreateArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KodWeryfikacyjnies.
   * @param {KodWeryfikacyjnyCreateManyArgs} args - Arguments to create many KodWeryfikacyjnies.
   * @example
   * // Create many KodWeryfikacyjnies
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KodWeryfikacyjnyCreateManyArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KodWeryfikacyjnies and returns the data saved in the database.
   * @param {KodWeryfikacyjnyCreateManyAndReturnArgs} args - Arguments to create many KodWeryfikacyjnies.
   * @example
   * // Create many KodWeryfikacyjnies
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KodWeryfikacyjnies and only return the `id`
   * const kodWeryfikacyjnyWithIdOnly = await prisma.kodWeryfikacyjny.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KodWeryfikacyjnyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KodWeryfikacyjny.
   * @param {KodWeryfikacyjnyDeleteArgs} args - Arguments to delete one KodWeryfikacyjny.
   * @example
   * // Delete one KodWeryfikacyjny
   * const KodWeryfikacyjny = await prisma.kodWeryfikacyjny.delete({
   *   where: {
   *     // ... filter to delete one KodWeryfikacyjny
   *   }
   * })
   * 
   */
  delete<T extends KodWeryfikacyjnyDeleteArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyDeleteArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KodWeryfikacyjny.
   * @param {KodWeryfikacyjnyUpdateArgs} args - Arguments to update one KodWeryfikacyjny.
   * @example
   * // Update one KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KodWeryfikacyjnyUpdateArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyUpdateArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KodWeryfikacyjnies.
   * @param {KodWeryfikacyjnyDeleteManyArgs} args - Arguments to filter KodWeryfikacyjnies to delete.
   * @example
   * // Delete a few KodWeryfikacyjnies
   * const { count } = await prisma.kodWeryfikacyjny.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KodWeryfikacyjnyDeleteManyArgs>(args?: Prisma.SelectSubset<T, KodWeryfikacyjnyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KodWeryfikacyjnies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KodWeryfikacyjnies
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KodWeryfikacyjnyUpdateManyArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KodWeryfikacyjnies and returns the data updated in the database.
   * @param {KodWeryfikacyjnyUpdateManyAndReturnArgs} args - Arguments to update many KodWeryfikacyjnies.
   * @example
   * // Update many KodWeryfikacyjnies
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KodWeryfikacyjnies and only return the `id`
   * const kodWeryfikacyjnyWithIdOnly = await prisma.kodWeryfikacyjny.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KodWeryfikacyjnyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KodWeryfikacyjny.
   * @param {KodWeryfikacyjnyUpsertArgs} args - Arguments to update or create a KodWeryfikacyjny.
   * @example
   * // Update or create a KodWeryfikacyjny
   * const kodWeryfikacyjny = await prisma.kodWeryfikacyjny.upsert({
   *   create: {
   *     // ... data to create a KodWeryfikacyjny
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KodWeryfikacyjny we want to update
   *   }
   * })
   */
  upsert<T extends KodWeryfikacyjnyUpsertArgs>(args: Prisma.SelectSubset<T, KodWeryfikacyjnyUpsertArgs<ExtArgs>>): Prisma.Prisma__KodWeryfikacyjnyClient<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KodWeryfikacyjnies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyCountArgs} args - Arguments to filter KodWeryfikacyjnies to count.
   * @example
   * // Count the number of KodWeryfikacyjnies
   * const count = await prisma.kodWeryfikacyjny.count({
   *   where: {
   *     // ... the filter for the KodWeryfikacyjnies we want to count
   *   }
   * })
  **/
  count<T extends KodWeryfikacyjnyCountArgs>(
    args?: Prisma.Subset<T, KodWeryfikacyjnyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KodWeryfikacyjnyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KodWeryfikacyjny.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KodWeryfikacyjnyAggregateArgs>(args: Prisma.Subset<T, KodWeryfikacyjnyAggregateArgs>): Prisma.PrismaPromise<GetKodWeryfikacyjnyAggregateType<T>>

  /**
   * Group by KodWeryfikacyjny.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KodWeryfikacyjnyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KodWeryfikacyjnyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KodWeryfikacyjnyGroupByArgs['orderBy'] }
      : { orderBy?: KodWeryfikacyjnyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KodWeryfikacyjnyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKodWeryfikacyjnyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KodWeryfikacyjny model
 */
readonly fields: KodWeryfikacyjnyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KodWeryfikacyjny.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KodWeryfikacyjnyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  uzytkownik<T extends Prisma.UzytkownikDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UzytkownikDefaultArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KodWeryfikacyjny model
 */
export interface KodWeryfikacyjnyFieldRefs {
  readonly id: Prisma.FieldRef<"KodWeryfikacyjny", 'String'>
  readonly uzytkownikId: Prisma.FieldRef<"KodWeryfikacyjny", 'String'>
  readonly kodHash: Prisma.FieldRef<"KodWeryfikacyjny", 'String'>
  readonly probyNieudane: Prisma.FieldRef<"KodWeryfikacyjny", 'Int'>
  readonly wygasaAt: Prisma.FieldRef<"KodWeryfikacyjny", 'DateTime'>
  readonly wykorzystanyAt: Prisma.FieldRef<"KodWeryfikacyjny", 'DateTime'>
  readonly utworzonyAt: Prisma.FieldRef<"KodWeryfikacyjny", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KodWeryfikacyjny findUnique
 */
export type KodWeryfikacyjnyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter, which KodWeryfikacyjny to fetch.
   */
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
}

/**
 * KodWeryfikacyjny findUniqueOrThrow
 */
export type KodWeryfikacyjnyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter, which KodWeryfikacyjny to fetch.
   */
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
}

/**
 * KodWeryfikacyjny findFirst
 */
export type KodWeryfikacyjnyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter, which KodWeryfikacyjny to fetch.
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KodWeryfikacyjnies to fetch.
   */
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithRelationInput | Prisma.KodWeryfikacyjnyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KodWeryfikacyjnies.
   */
  cursor?: Prisma.KodWeryfikacyjnyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KodWeryfikacyjnies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KodWeryfikacyjnies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KodWeryfikacyjnies.
   */
  distinct?: Prisma.KodWeryfikacyjnyScalarFieldEnum | Prisma.KodWeryfikacyjnyScalarFieldEnum[]
}

/**
 * KodWeryfikacyjny findFirstOrThrow
 */
export type KodWeryfikacyjnyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter, which KodWeryfikacyjny to fetch.
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KodWeryfikacyjnies to fetch.
   */
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithRelationInput | Prisma.KodWeryfikacyjnyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KodWeryfikacyjnies.
   */
  cursor?: Prisma.KodWeryfikacyjnyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KodWeryfikacyjnies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KodWeryfikacyjnies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KodWeryfikacyjnies.
   */
  distinct?: Prisma.KodWeryfikacyjnyScalarFieldEnum | Prisma.KodWeryfikacyjnyScalarFieldEnum[]
}

/**
 * KodWeryfikacyjny findMany
 */
export type KodWeryfikacyjnyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter, which KodWeryfikacyjnies to fetch.
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KodWeryfikacyjnies to fetch.
   */
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithRelationInput | Prisma.KodWeryfikacyjnyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KodWeryfikacyjnies.
   */
  cursor?: Prisma.KodWeryfikacyjnyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KodWeryfikacyjnies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KodWeryfikacyjnies.
   */
  skip?: number
  distinct?: Prisma.KodWeryfikacyjnyScalarFieldEnum | Prisma.KodWeryfikacyjnyScalarFieldEnum[]
}

/**
 * KodWeryfikacyjny create
 */
export type KodWeryfikacyjnyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * The data needed to create a KodWeryfikacyjny.
   */
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateInput, Prisma.KodWeryfikacyjnyUncheckedCreateInput>
}

/**
 * KodWeryfikacyjny createMany
 */
export type KodWeryfikacyjnyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KodWeryfikacyjnies.
   */
  data: Prisma.KodWeryfikacyjnyCreateManyInput | Prisma.KodWeryfikacyjnyCreateManyInput[]
}

/**
 * KodWeryfikacyjny createManyAndReturn
 */
export type KodWeryfikacyjnyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * The data used to create many KodWeryfikacyjnies.
   */
  data: Prisma.KodWeryfikacyjnyCreateManyInput | Prisma.KodWeryfikacyjnyCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KodWeryfikacyjny update
 */
export type KodWeryfikacyjnyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * The data needed to update a KodWeryfikacyjny.
   */
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateInput, Prisma.KodWeryfikacyjnyUncheckedUpdateInput>
  /**
   * Choose, which KodWeryfikacyjny to update.
   */
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
}

/**
 * KodWeryfikacyjny updateMany
 */
export type KodWeryfikacyjnyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KodWeryfikacyjnies.
   */
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateManyMutationInput, Prisma.KodWeryfikacyjnyUncheckedUpdateManyInput>
  /**
   * Filter which KodWeryfikacyjnies to update
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * Limit how many KodWeryfikacyjnies to update.
   */
  limit?: number
}

/**
 * KodWeryfikacyjny updateManyAndReturn
 */
export type KodWeryfikacyjnyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * The data used to update KodWeryfikacyjnies.
   */
  data: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateManyMutationInput, Prisma.KodWeryfikacyjnyUncheckedUpdateManyInput>
  /**
   * Filter which KodWeryfikacyjnies to update
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * Limit how many KodWeryfikacyjnies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KodWeryfikacyjny upsert
 */
export type KodWeryfikacyjnyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * The filter to search for the KodWeryfikacyjny to update in case it exists.
   */
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
  /**
   * In case the KodWeryfikacyjny found by the `where` argument doesn't exist, create a new KodWeryfikacyjny with this data.
   */
  create: Prisma.XOR<Prisma.KodWeryfikacyjnyCreateInput, Prisma.KodWeryfikacyjnyUncheckedCreateInput>
  /**
   * In case the KodWeryfikacyjny was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KodWeryfikacyjnyUpdateInput, Prisma.KodWeryfikacyjnyUncheckedUpdateInput>
}

/**
 * KodWeryfikacyjny delete
 */
export type KodWeryfikacyjnyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  /**
   * Filter which KodWeryfikacyjny to delete.
   */
  where: Prisma.KodWeryfikacyjnyWhereUniqueInput
}

/**
 * KodWeryfikacyjny deleteMany
 */
export type KodWeryfikacyjnyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KodWeryfikacyjnies to delete
   */
  where?: Prisma.KodWeryfikacyjnyWhereInput
  /**
   * Limit how many KodWeryfikacyjnies to delete.
   */
  limit?: number
}

/**
 * KodWeryfikacyjny without action
 */
export type KodWeryfikacyjnyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
}
