
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Uzytkownik` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Uzytkownik
 * 
 */
export type UzytkownikModel = runtime.Types.Result.DefaultSelection<Prisma.$UzytkownikPayload>

export type AggregateUzytkownik = {
  _count: UzytkownikCountAggregateOutputType | null
  _min: UzytkownikMinAggregateOutputType | null
  _max: UzytkownikMaxAggregateOutputType | null
}

export type UzytkownikMinAggregateOutputType = {
  id: string | null
  email: string | null
  hashHasla: string | null
  zweryfikowanyAt: Date | null
  utworzonyAt: Date | null
}

export type UzytkownikMaxAggregateOutputType = {
  id: string | null
  email: string | null
  hashHasla: string | null
  zweryfikowanyAt: Date | null
  utworzonyAt: Date | null
}

export type UzytkownikCountAggregateOutputType = {
  id: number
  email: number
  hashHasla: number
  zweryfikowanyAt: number
  utworzonyAt: number
  _all: number
}


export type UzytkownikMinAggregateInputType = {
  id?: true
  email?: true
  hashHasla?: true
  zweryfikowanyAt?: true
  utworzonyAt?: true
}

export type UzytkownikMaxAggregateInputType = {
  id?: true
  email?: true
  hashHasla?: true
  zweryfikowanyAt?: true
  utworzonyAt?: true
}

export type UzytkownikCountAggregateInputType = {
  id?: true
  email?: true
  hashHasla?: true
  zweryfikowanyAt?: true
  utworzonyAt?: true
  _all?: true
}

export type UzytkownikAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Uzytkownik to aggregate.
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uzytkowniks to fetch.
   */
  orderBy?: Prisma.UzytkownikOrderByWithRelationInput | Prisma.UzytkownikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UzytkownikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uzytkowniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uzytkowniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Uzytkowniks
  **/
  _count?: true | UzytkownikCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UzytkownikMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UzytkownikMaxAggregateInputType
}

export type GetUzytkownikAggregateType<T extends UzytkownikAggregateArgs> = {
      [P in keyof T & keyof AggregateUzytkownik]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUzytkownik[P]>
    : Prisma.GetScalarType<T[P], AggregateUzytkownik[P]>
}




export type UzytkownikGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UzytkownikWhereInput
  orderBy?: Prisma.UzytkownikOrderByWithAggregationInput | Prisma.UzytkownikOrderByWithAggregationInput[]
  by: Prisma.UzytkownikScalarFieldEnum[] | Prisma.UzytkownikScalarFieldEnum
  having?: Prisma.UzytkownikScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UzytkownikCountAggregateInputType | true
  _min?: UzytkownikMinAggregateInputType
  _max?: UzytkownikMaxAggregateInputType
}

export type UzytkownikGroupByOutputType = {
  id: string
  email: string
  hashHasla: string
  zweryfikowanyAt: Date | null
  utworzonyAt: Date
  _count: UzytkownikCountAggregateOutputType | null
  _min: UzytkownikMinAggregateOutputType | null
  _max: UzytkownikMaxAggregateOutputType | null
}

type GetUzytkownikGroupByPayload<T extends UzytkownikGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UzytkownikGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UzytkownikGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UzytkownikGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UzytkownikGroupByOutputType[P]>
      }
    >
  >



export type UzytkownikWhereInput = {
  AND?: Prisma.UzytkownikWhereInput | Prisma.UzytkownikWhereInput[]
  OR?: Prisma.UzytkownikWhereInput[]
  NOT?: Prisma.UzytkownikWhereInput | Prisma.UzytkownikWhereInput[]
  id?: Prisma.StringFilter<"Uzytkownik"> | string
  email?: Prisma.StringFilter<"Uzytkownik"> | string
  hashHasla?: Prisma.StringFilter<"Uzytkownik"> | string
  zweryfikowanyAt?: Prisma.DateTimeNullableFilter<"Uzytkownik"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeFilter<"Uzytkownik"> | Date | string
  kody?: Prisma.KodWeryfikacyjnyListRelationFilter
}

export type UzytkownikOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashHasla?: Prisma.SortOrder
  zweryfikowanyAt?: Prisma.SortOrderInput | Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
  kody?: Prisma.KodWeryfikacyjnyOrderByRelationAggregateInput
}

export type UzytkownikWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UzytkownikWhereInput | Prisma.UzytkownikWhereInput[]
  OR?: Prisma.UzytkownikWhereInput[]
  NOT?: Prisma.UzytkownikWhereInput | Prisma.UzytkownikWhereInput[]
  hashHasla?: Prisma.StringFilter<"Uzytkownik"> | string
  zweryfikowanyAt?: Prisma.DateTimeNullableFilter<"Uzytkownik"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeFilter<"Uzytkownik"> | Date | string
  kody?: Prisma.KodWeryfikacyjnyListRelationFilter
}, "id" | "email">

export type UzytkownikOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashHasla?: Prisma.SortOrder
  zweryfikowanyAt?: Prisma.SortOrderInput | Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
  _count?: Prisma.UzytkownikCountOrderByAggregateInput
  _max?: Prisma.UzytkownikMaxOrderByAggregateInput
  _min?: Prisma.UzytkownikMinOrderByAggregateInput
}

export type UzytkownikScalarWhereWithAggregatesInput = {
  AND?: Prisma.UzytkownikScalarWhereWithAggregatesInput | Prisma.UzytkownikScalarWhereWithAggregatesInput[]
  OR?: Prisma.UzytkownikScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UzytkownikScalarWhereWithAggregatesInput | Prisma.UzytkownikScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Uzytkownik"> | string
  email?: Prisma.StringWithAggregatesFilter<"Uzytkownik"> | string
  hashHasla?: Prisma.StringWithAggregatesFilter<"Uzytkownik"> | string
  zweryfikowanyAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Uzytkownik"> | Date | string | null
  utworzonyAt?: Prisma.DateTimeWithAggregatesFilter<"Uzytkownik"> | Date | string
}

export type UzytkownikCreateInput = {
  id?: string
  email: string
  hashHasla: string
  zweryfikowanyAt?: Date | string | null
  utworzonyAt?: Date | string
  kody?: Prisma.KodWeryfikacyjnyCreateNestedManyWithoutUzytkownikInput
}

export type UzytkownikUncheckedCreateInput = {
  id?: string
  email: string
  hashHasla: string
  zweryfikowanyAt?: Date | string | null
  utworzonyAt?: Date | string
  kody?: Prisma.KodWeryfikacyjnyUncheckedCreateNestedManyWithoutUzytkownikInput
}

export type UzytkownikUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kody?: Prisma.KodWeryfikacyjnyUpdateManyWithoutUzytkownikNestedInput
}

export type UzytkownikUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kody?: Prisma.KodWeryfikacyjnyUncheckedUpdateManyWithoutUzytkownikNestedInput
}

export type UzytkownikCreateManyInput = {
  id?: string
  email: string
  hashHasla: string
  zweryfikowanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type UzytkownikUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UzytkownikUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UzytkownikCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashHasla?: Prisma.SortOrder
  zweryfikowanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type UzytkownikMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashHasla?: Prisma.SortOrder
  zweryfikowanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type UzytkownikMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashHasla?: Prisma.SortOrder
  zweryfikowanyAt?: Prisma.SortOrder
  utworzonyAt?: Prisma.SortOrder
}

export type UzytkownikScalarRelationFilter = {
  is?: Prisma.UzytkownikWhereInput
  isNot?: Prisma.UzytkownikWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UzytkownikCreateNestedOneWithoutKodyInput = {
  create?: Prisma.XOR<Prisma.UzytkownikCreateWithoutKodyInput, Prisma.UzytkownikUncheckedCreateWithoutKodyInput>
  connectOrCreate?: Prisma.UzytkownikCreateOrConnectWithoutKodyInput
  connect?: Prisma.UzytkownikWhereUniqueInput
}

export type UzytkownikUpdateOneRequiredWithoutKodyNestedInput = {
  create?: Prisma.XOR<Prisma.UzytkownikCreateWithoutKodyInput, Prisma.UzytkownikUncheckedCreateWithoutKodyInput>
  connectOrCreate?: Prisma.UzytkownikCreateOrConnectWithoutKodyInput
  upsert?: Prisma.UzytkownikUpsertWithoutKodyInput
  connect?: Prisma.UzytkownikWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UzytkownikUpdateToOneWithWhereWithoutKodyInput, Prisma.UzytkownikUpdateWithoutKodyInput>, Prisma.UzytkownikUncheckedUpdateWithoutKodyInput>
}

export type UzytkownikCreateWithoutKodyInput = {
  id?: string
  email: string
  hashHasla: string
  zweryfikowanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type UzytkownikUncheckedCreateWithoutKodyInput = {
  id?: string
  email: string
  hashHasla: string
  zweryfikowanyAt?: Date | string | null
  utworzonyAt?: Date | string
}

export type UzytkownikCreateOrConnectWithoutKodyInput = {
  where: Prisma.UzytkownikWhereUniqueInput
  create: Prisma.XOR<Prisma.UzytkownikCreateWithoutKodyInput, Prisma.UzytkownikUncheckedCreateWithoutKodyInput>
}

export type UzytkownikUpsertWithoutKodyInput = {
  update: Prisma.XOR<Prisma.UzytkownikUpdateWithoutKodyInput, Prisma.UzytkownikUncheckedUpdateWithoutKodyInput>
  create: Prisma.XOR<Prisma.UzytkownikCreateWithoutKodyInput, Prisma.UzytkownikUncheckedCreateWithoutKodyInput>
  where?: Prisma.UzytkownikWhereInput
}

export type UzytkownikUpdateToOneWithWhereWithoutKodyInput = {
  where?: Prisma.UzytkownikWhereInput
  data: Prisma.XOR<Prisma.UzytkownikUpdateWithoutKodyInput, Prisma.UzytkownikUncheckedUpdateWithoutKodyInput>
}

export type UzytkownikUpdateWithoutKodyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UzytkownikUncheckedUpdateWithoutKodyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashHasla?: Prisma.StringFieldUpdateOperationsInput | string
  zweryfikowanyAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  utworzonyAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UzytkownikCountOutputType
 */

export type UzytkownikCountOutputType = {
  kody: number
}

export type UzytkownikCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kody?: boolean | UzytkownikCountOutputTypeCountKodyArgs
}

/**
 * UzytkownikCountOutputType without action
 */
export type UzytkownikCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UzytkownikCountOutputType
   */
  select?: Prisma.UzytkownikCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UzytkownikCountOutputType without action
 */
export type UzytkownikCountOutputTypeCountKodyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KodWeryfikacyjnyWhereInput
}


export type UzytkownikSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashHasla?: boolean
  zweryfikowanyAt?: boolean
  utworzonyAt?: boolean
  kody?: boolean | Prisma.Uzytkownik$kodyArgs<ExtArgs>
  _count?: boolean | Prisma.UzytkownikCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["uzytkownik"]>

export type UzytkownikSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashHasla?: boolean
  zweryfikowanyAt?: boolean
  utworzonyAt?: boolean
}, ExtArgs["result"]["uzytkownik"]>

export type UzytkownikSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashHasla?: boolean
  zweryfikowanyAt?: boolean
  utworzonyAt?: boolean
}, ExtArgs["result"]["uzytkownik"]>

export type UzytkownikSelectScalar = {
  id?: boolean
  email?: boolean
  hashHasla?: boolean
  zweryfikowanyAt?: boolean
  utworzonyAt?: boolean
}

export type UzytkownikOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "hashHasla" | "zweryfikowanyAt" | "utworzonyAt", ExtArgs["result"]["uzytkownik"]>
export type UzytkownikInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kody?: boolean | Prisma.Uzytkownik$kodyArgs<ExtArgs>
  _count?: boolean | Prisma.UzytkownikCountOutputTypeDefaultArgs<ExtArgs>
}
export type UzytkownikIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UzytkownikIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UzytkownikPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Uzytkownik"
  objects: {
    kody: Prisma.$KodWeryfikacyjnyPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    hashHasla: string
    zweryfikowanyAt: Date | null
    utworzonyAt: Date
  }, ExtArgs["result"]["uzytkownik"]>
  composites: {}
}

export type UzytkownikGetPayload<S extends boolean | null | undefined | UzytkownikDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload, S>

export type UzytkownikCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UzytkownikFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UzytkownikCountAggregateInputType | true
  }

export interface UzytkownikDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Uzytkownik'], meta: { name: 'Uzytkownik' } }
  /**
   * Find zero or one Uzytkownik that matches the filter.
   * @param {UzytkownikFindUniqueArgs} args - Arguments to find a Uzytkownik
   * @example
   * // Get one Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UzytkownikFindUniqueArgs>(args: Prisma.SelectSubset<T, UzytkownikFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Uzytkownik that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UzytkownikFindUniqueOrThrowArgs} args - Arguments to find a Uzytkownik
   * @example
   * // Get one Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UzytkownikFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UzytkownikFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Uzytkownik that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikFindFirstArgs} args - Arguments to find a Uzytkownik
   * @example
   * // Get one Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UzytkownikFindFirstArgs>(args?: Prisma.SelectSubset<T, UzytkownikFindFirstArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Uzytkownik that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikFindFirstOrThrowArgs} args - Arguments to find a Uzytkownik
   * @example
   * // Get one Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UzytkownikFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UzytkownikFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Uzytkowniks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Uzytkowniks
   * const uzytkowniks = await prisma.uzytkownik.findMany()
   * 
   * // Get first 10 Uzytkowniks
   * const uzytkowniks = await prisma.uzytkownik.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const uzytkownikWithIdOnly = await prisma.uzytkownik.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UzytkownikFindManyArgs>(args?: Prisma.SelectSubset<T, UzytkownikFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Uzytkownik.
   * @param {UzytkownikCreateArgs} args - Arguments to create a Uzytkownik.
   * @example
   * // Create one Uzytkownik
   * const Uzytkownik = await prisma.uzytkownik.create({
   *   data: {
   *     // ... data to create a Uzytkownik
   *   }
   * })
   * 
   */
  create<T extends UzytkownikCreateArgs>(args: Prisma.SelectSubset<T, UzytkownikCreateArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Uzytkowniks.
   * @param {UzytkownikCreateManyArgs} args - Arguments to create many Uzytkowniks.
   * @example
   * // Create many Uzytkowniks
   * const uzytkownik = await prisma.uzytkownik.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UzytkownikCreateManyArgs>(args?: Prisma.SelectSubset<T, UzytkownikCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Uzytkowniks and returns the data saved in the database.
   * @param {UzytkownikCreateManyAndReturnArgs} args - Arguments to create many Uzytkowniks.
   * @example
   * // Create many Uzytkowniks
   * const uzytkownik = await prisma.uzytkownik.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Uzytkowniks and only return the `id`
   * const uzytkownikWithIdOnly = await prisma.uzytkownik.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UzytkownikCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UzytkownikCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Uzytkownik.
   * @param {UzytkownikDeleteArgs} args - Arguments to delete one Uzytkownik.
   * @example
   * // Delete one Uzytkownik
   * const Uzytkownik = await prisma.uzytkownik.delete({
   *   where: {
   *     // ... filter to delete one Uzytkownik
   *   }
   * })
   * 
   */
  delete<T extends UzytkownikDeleteArgs>(args: Prisma.SelectSubset<T, UzytkownikDeleteArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Uzytkownik.
   * @param {UzytkownikUpdateArgs} args - Arguments to update one Uzytkownik.
   * @example
   * // Update one Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UzytkownikUpdateArgs>(args: Prisma.SelectSubset<T, UzytkownikUpdateArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Uzytkowniks.
   * @param {UzytkownikDeleteManyArgs} args - Arguments to filter Uzytkowniks to delete.
   * @example
   * // Delete a few Uzytkowniks
   * const { count } = await prisma.uzytkownik.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UzytkownikDeleteManyArgs>(args?: Prisma.SelectSubset<T, UzytkownikDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Uzytkowniks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Uzytkowniks
   * const uzytkownik = await prisma.uzytkownik.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UzytkownikUpdateManyArgs>(args: Prisma.SelectSubset<T, UzytkownikUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Uzytkowniks and returns the data updated in the database.
   * @param {UzytkownikUpdateManyAndReturnArgs} args - Arguments to update many Uzytkowniks.
   * @example
   * // Update many Uzytkowniks
   * const uzytkownik = await prisma.uzytkownik.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Uzytkowniks and only return the `id`
   * const uzytkownikWithIdOnly = await prisma.uzytkownik.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UzytkownikUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UzytkownikUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Uzytkownik.
   * @param {UzytkownikUpsertArgs} args - Arguments to update or create a Uzytkownik.
   * @example
   * // Update or create a Uzytkownik
   * const uzytkownik = await prisma.uzytkownik.upsert({
   *   create: {
   *     // ... data to create a Uzytkownik
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Uzytkownik we want to update
   *   }
   * })
   */
  upsert<T extends UzytkownikUpsertArgs>(args: Prisma.SelectSubset<T, UzytkownikUpsertArgs<ExtArgs>>): Prisma.Prisma__UzytkownikClient<runtime.Types.Result.GetResult<Prisma.$UzytkownikPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Uzytkowniks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikCountArgs} args - Arguments to filter Uzytkowniks to count.
   * @example
   * // Count the number of Uzytkowniks
   * const count = await prisma.uzytkownik.count({
   *   where: {
   *     // ... the filter for the Uzytkowniks we want to count
   *   }
   * })
  **/
  count<T extends UzytkownikCountArgs>(
    args?: Prisma.Subset<T, UzytkownikCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UzytkownikCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Uzytkownik.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UzytkownikAggregateArgs>(args: Prisma.Subset<T, UzytkownikAggregateArgs>): Prisma.PrismaPromise<GetUzytkownikAggregateType<T>>

  /**
   * Group by Uzytkownik.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UzytkownikGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UzytkownikGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UzytkownikGroupByArgs['orderBy'] }
      : { orderBy?: UzytkownikGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UzytkownikGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUzytkownikGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Uzytkownik model
 */
readonly fields: UzytkownikFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Uzytkownik.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UzytkownikClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kody<T extends Prisma.Uzytkownik$kodyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Uzytkownik$kodyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KodWeryfikacyjnyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Uzytkownik model
 */
export interface UzytkownikFieldRefs {
  readonly id: Prisma.FieldRef<"Uzytkownik", 'String'>
  readonly email: Prisma.FieldRef<"Uzytkownik", 'String'>
  readonly hashHasla: Prisma.FieldRef<"Uzytkownik", 'String'>
  readonly zweryfikowanyAt: Prisma.FieldRef<"Uzytkownik", 'DateTime'>
  readonly utworzonyAt: Prisma.FieldRef<"Uzytkownik", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Uzytkownik findUnique
 */
export type UzytkownikFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter, which Uzytkownik to fetch.
   */
  where: Prisma.UzytkownikWhereUniqueInput
}

/**
 * Uzytkownik findUniqueOrThrow
 */
export type UzytkownikFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter, which Uzytkownik to fetch.
   */
  where: Prisma.UzytkownikWhereUniqueInput
}

/**
 * Uzytkownik findFirst
 */
export type UzytkownikFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter, which Uzytkownik to fetch.
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uzytkowniks to fetch.
   */
  orderBy?: Prisma.UzytkownikOrderByWithRelationInput | Prisma.UzytkownikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Uzytkowniks.
   */
  cursor?: Prisma.UzytkownikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uzytkowniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uzytkowniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Uzytkowniks.
   */
  distinct?: Prisma.UzytkownikScalarFieldEnum | Prisma.UzytkownikScalarFieldEnum[]
}

/**
 * Uzytkownik findFirstOrThrow
 */
export type UzytkownikFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter, which Uzytkownik to fetch.
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uzytkowniks to fetch.
   */
  orderBy?: Prisma.UzytkownikOrderByWithRelationInput | Prisma.UzytkownikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Uzytkowniks.
   */
  cursor?: Prisma.UzytkownikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uzytkowniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uzytkowniks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Uzytkowniks.
   */
  distinct?: Prisma.UzytkownikScalarFieldEnum | Prisma.UzytkownikScalarFieldEnum[]
}

/**
 * Uzytkownik findMany
 */
export type UzytkownikFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter, which Uzytkowniks to fetch.
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uzytkowniks to fetch.
   */
  orderBy?: Prisma.UzytkownikOrderByWithRelationInput | Prisma.UzytkownikOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Uzytkowniks.
   */
  cursor?: Prisma.UzytkownikWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uzytkowniks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uzytkowniks.
   */
  skip?: number
  distinct?: Prisma.UzytkownikScalarFieldEnum | Prisma.UzytkownikScalarFieldEnum[]
}

/**
 * Uzytkownik create
 */
export type UzytkownikCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * The data needed to create a Uzytkownik.
   */
  data: Prisma.XOR<Prisma.UzytkownikCreateInput, Prisma.UzytkownikUncheckedCreateInput>
}

/**
 * Uzytkownik createMany
 */
export type UzytkownikCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Uzytkowniks.
   */
  data: Prisma.UzytkownikCreateManyInput | Prisma.UzytkownikCreateManyInput[]
}

/**
 * Uzytkownik createManyAndReturn
 */
export type UzytkownikCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * The data used to create many Uzytkowniks.
   */
  data: Prisma.UzytkownikCreateManyInput | Prisma.UzytkownikCreateManyInput[]
}

/**
 * Uzytkownik update
 */
export type UzytkownikUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * The data needed to update a Uzytkownik.
   */
  data: Prisma.XOR<Prisma.UzytkownikUpdateInput, Prisma.UzytkownikUncheckedUpdateInput>
  /**
   * Choose, which Uzytkownik to update.
   */
  where: Prisma.UzytkownikWhereUniqueInput
}

/**
 * Uzytkownik updateMany
 */
export type UzytkownikUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Uzytkowniks.
   */
  data: Prisma.XOR<Prisma.UzytkownikUpdateManyMutationInput, Prisma.UzytkownikUncheckedUpdateManyInput>
  /**
   * Filter which Uzytkowniks to update
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * Limit how many Uzytkowniks to update.
   */
  limit?: number
}

/**
 * Uzytkownik updateManyAndReturn
 */
export type UzytkownikUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * The data used to update Uzytkowniks.
   */
  data: Prisma.XOR<Prisma.UzytkownikUpdateManyMutationInput, Prisma.UzytkownikUncheckedUpdateManyInput>
  /**
   * Filter which Uzytkowniks to update
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * Limit how many Uzytkowniks to update.
   */
  limit?: number
}

/**
 * Uzytkownik upsert
 */
export type UzytkownikUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * The filter to search for the Uzytkownik to update in case it exists.
   */
  where: Prisma.UzytkownikWhereUniqueInput
  /**
   * In case the Uzytkownik found by the `where` argument doesn't exist, create a new Uzytkownik with this data.
   */
  create: Prisma.XOR<Prisma.UzytkownikCreateInput, Prisma.UzytkownikUncheckedCreateInput>
  /**
   * In case the Uzytkownik was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UzytkownikUpdateInput, Prisma.UzytkownikUncheckedUpdateInput>
}

/**
 * Uzytkownik delete
 */
export type UzytkownikDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
  /**
   * Filter which Uzytkownik to delete.
   */
  where: Prisma.UzytkownikWhereUniqueInput
}

/**
 * Uzytkownik deleteMany
 */
export type UzytkownikDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Uzytkowniks to delete
   */
  where?: Prisma.UzytkownikWhereInput
  /**
   * Limit how many Uzytkowniks to delete.
   */
  limit?: number
}

/**
 * Uzytkownik.kody
 */
export type Uzytkownik$kodyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KodWeryfikacyjny
   */
  select?: Prisma.KodWeryfikacyjnySelect<ExtArgs> | null
  /**
   * Omit specific fields from the KodWeryfikacyjny
   */
  omit?: Prisma.KodWeryfikacyjnyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KodWeryfikacyjnyInclude<ExtArgs> | null
  where?: Prisma.KodWeryfikacyjnyWhereInput
  orderBy?: Prisma.KodWeryfikacyjnyOrderByWithRelationInput | Prisma.KodWeryfikacyjnyOrderByWithRelationInput[]
  cursor?: Prisma.KodWeryfikacyjnyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KodWeryfikacyjnyScalarFieldEnum | Prisma.KodWeryfikacyjnyScalarFieldEnum[]
}

/**
 * Uzytkownik without action
 */
export type UzytkownikDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Uzytkownik
   */
  select?: Prisma.UzytkownikSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Uzytkownik
   */
  omit?: Prisma.UzytkownikOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UzytkownikInclude<ExtArgs> | null
}
